include classpath("application.conf")

queues {
  "freight-watchtower.fifo" {
    fifo = true
    defaultVisibilityTimeout = 60 seconds
    delay = 0 seconds
    receiveMessageWait = 0 seconds
    deadLettersQueue {
      name = "freight-watchtower-dlq.fifo"
      maxReceiveCount = 3
    }
  }
  "freight-watchtower-dlq.fifo" {
    fifo = true
  }
}
